# Site settings
title: Jaded Biologist
description: 'Musings of Wetlab Biologist & Bioinformatician'
url: 'https://alexhuszagh.github.io'
google_analytics: 'UA-86636302-1'
disqus_shortname: 'https-alexhuszagh-github-io'

# About
author:
  name: 'Alex Huszagh'
  email: ahuszagh@gmail.com
  twitter_username: Alexhuszagh
  facebook_username: alexhuszagh
  github_username:  Alexhuszagh
  linkedin_username: alexhuszagh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
